### ISSUE TITLE
Determine language & web framework for server

### ISSUE THREAD

**Issue by dave2000sang** [dave2000sang/Trackuriboh-server#2]

**Comment by dave2000sang** [comment]
[Gin](https://github.com/gin-gonic/gin) is a fast and lightweight framework

Just use stdlib http/net package

**Comment by 1298se** [comment]
I see. Looks good, seems like most popular GO framework. And for server I am thinking Mongo, although not sure if the discrepancy between Android and server will bite us in future. I don't think so because they're separate?

Mongo seems to be nice because we probably need to optimize reads due to the client database syncs. We are only gonna do 1 set of writes a day so it should be fine
